# Generated by Django 5.2.7 on 2025-10-04 02:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("source", models.CharField(blank=True, max_length=100, null=True)),
                ("level", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
